version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ".:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "ironfloor881"
      # enable env variable replacement
      # REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
    restart: always
volumes:
  mc:
